export type { default as Patient } from './Patient'
export type { default as SearchPatient } from './SearchPatient'
export type { default as Sort } from './Sort'
export type { default as Pageable } from './Pageable'
export type { default as SearchPatientBody } from './SearchPatientBody'
export type { default as Appointment} from './Appointment'
export type { default as SearchAppointment} from './SearchAppointment'
export type { default as SearchAppointmentBody} from './SearchAppointmentBody'
export type { default as Address} from './Address'