export type { default as CreatePatientResponse} from './CreatePatientResponse'
export type { default as DeletePatientResponse} from './DeletePatientResponse'
export type { default as ReadPatientReponse} from './ReadPatientResponse'
export type { default as SearchPatientResponse} from './SearchPatientResponse'
export type { default as UpdatePatientResponse} from './UpdatePatientResponse' 