export { default as Welcome } from './Welcome/Welcome'
export { default as AppointmentArea } from './AppointmentArea/AppointmentArea'
export {default as NewAppointment} from './NewAppointment/NewAppointment'
export { default as UrgentCommunication} from './UrgentCommunication/UrgentCommunication'
export { default as UserInformation} from './UserInformation/UserInformation'