export type { default as CreateAppointmentResponse } from './CreateAppointmentResponse'
export type { default as DeleteAppointmentResponse } from './DeleteAppointmentResponse'
export type { default as ReadAppointmentResponse } from './ReadAppointmentResponse'
export type { default as SearchAppointmentReponse } from './SearchAppointmentResponse'
export type { default as UpdateAppointmentResponse } from './UpdateAppointmentResponse'